#!/bin/sh
BASEDIR=`dirname "$0"`
REPO="${BASEDIR}/../Resources/Java/repo"

CP="`ls "${REPO}"/org/fusesource/hawtjni/hawtjni-ui/*/hawtjni-ui-*.jar`"
CP="${CP}:`ls "${REPO}"/org/fusesource/hawtjni/hawtjni-generator/*/hawtjni-generator-*.jar`"
CP="${CP}:`ls "${REPO}"/org/fusesource/hawtjni/hawtjni-runtime/*/hawtjni-runtime-*.jar`"
CP="${CP}:`ls "${REPO}"/org/fusesource/swt/swt/*/swt-*.jar`"

exec java \
	-XstartOnFirstThread \
	-classpath "${CP}" \
	-Dorg.eclipse.swt.internal.carbon.smallFonts \
	org.fusesource.hawtjni.ui.MacGeneratorUI
